function skillMember() {
    this.name = "Member";
    this.id = "member";
    this.icon = "icon-member";
    this.description = "Member";
    this.start = 0;
    this.end = 0;
    this.deadline = 0;
    this.duration = 0;
    this.isSkill = true;
    this.isMember = true;
    this.isLeader = false;
    this.isTask = false;
    this.isSprint = false;
    this.isStory = false;
    this.isBacklog = false;
    this.isProject = false;
    this.isProduct = false;
    this.isCompany = false;
}
